export const HOME = '/'
export const ARTICLES = '/articles'
export const ARTICLE_DETAILS = '/articles/:slug'
export const ARTICLE_EDIT = '/articles/:slug/edit'
export const SIGN_UP = '/sign-up'
export const SIGN_IN = '/sign-in'
export const PROFILE = '/profile'
export const NEW_ARTICLE = '/new-article'
